id: I1C111D97
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T13:44:15+00:00'
last_modified: '2022-06-08T13:40:58.497070+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC283
  title: དུས་སྟོན་བཀྲ་ཤིས་ཁ་གཡང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    9A9E:
      image_group_id: I2PD18376
      title: ''
      total_pages: 264
      order: 1
      base_file: 9A9E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
