id: P010448
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1AC283
  title: དུས་སྟོན་བཀྲ་ཤིས་ཁ་གཡང་།
  author: ''
  volumes:
    4e6f9b4bfcaa4082a697cc2ebe76b0c7:
      image_group_id: I2PD18376
      title: ''
      volume_number: 1
      total_pages: 264
      base_file: v001.txt
